In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense,Dropout,MaxPooling1D, Flatten,BatchNormalization, GaussianNoise,Conv1D
import matplotlib.pyplot as plt
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from sklearn.utils import compute_class_weight
from tensorflow.keras import initializers
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential, save_model, load_model

In [2]:
#this was created in general/diagnosis_making notebook
diag = pd.read_csv("ground_truth.csv").drop("Unnamed: 0", axis=1)

In [3]:
demo = pd.read_csv("PTDEMOG.csv")

In [4]:
demo

,Phase,ID,RID,SITEID,VISCODE,VISCODE2,USERDATE,USERDATE2,PTSOURCE,PTGENDER,...,PTTLANG,PTPLANG,PTPSPEC,PTCOGBEG,PTMCIBEG,PTADBEG,PTADDX,PTETHCAT,PTRACCAT,update_stamp
0,ADNI1,18,2,107,sc,sc,2005-08-17,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,-4.0,NaN,2.0,5.0,2005-08-17 00:00:00.0
1,ADNI1,20,1,10,f,f,2005-08-18,NaN,1,2.0,...,-4.0,-4.0,-4,NaN,NaN,-4.0,NaN,-4.0,-4.0,2005-08-18 00:00:00.0
2,ADNI1,22,3,107,sc,sc,2005-08-18,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,1999.0,NaN,2.0,5.0,2005-08-18 00:00:00.0
3,ADNI1,24,4,10,sc,sc,2005-08-18,NaN,1,1.0,...,2.0,2.0,-4,NaN,NaN,-4.0,NaN,1.0,5.0,2005-08-18 00:00:00.0
4,ADNI1,26,5,107,sc,sc,2005-08-23,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,-4.0,NaN,2.0,5.0,2005-08-23 00:00:00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4757,ADNI3,147284,7029,33,sc,sc,2021-11-22,2021-11-22,1,2.0,...,1.0,1.0,NaN,9999.0,NaN,NaN,9999.0,2.0,4.0,2021-11-23 04:20:20.0
4758,ADNI3,147547,7030,25,sc,sc,2021-11-30,2021-11-30,1,2.0,...,1.0,3.0,Ethiopian,9999.0,NaN,NaN,9999.0,2.0,4.0,2021-11-30 04:19:40.0
4759,ADNI3,147910,7031,25,sc,sc,2021-12-02,2021-12-02,1,2.0,...,1.0,1.0,NaN,2019.0,NaN,NaN,9999.0,2.0,4.0,2021-12-03 04:19:39.0
4760,ADNI3,147946,7032,51,sc,sc,2021-12-03,2021-12-03,1,1.0,...,1.0,1.0,NaN,2018.0,NaN,NaN,9999.0,2.0,5.0,2021-12-04 04:19:40.0
4761,ADNI3,148380,7033,33,sc,sc,2021-12-08,2021-12-08,1,2.0,...,1.0,1.0,NaN,2020.0,NaN,NaN,2021.0,2.0,4.0,2021-12-09 04:19:40.0

In [5]:
neuro = pd.read_csv("NEUROEXM.csv")

In [6]:
neuro.columns

Index(['Phase', 'ID', 'RID', 'SITEID', 'VISCODE', 'VISCODE2', 'USERDATE',
       'USERDATE2', 'EXAMDATE', 'NXVISUAL', 'NXVISDES', 'NXAUDITO', 'NXAUDDES',
       'NXTREMOR', 'NXTREDES', 'NXCONSCI', 'NXCONDES', 'NXNERVE', 'NXNERDES',
       'NXMOTOR', 'NXMOTDES', 'NXFINGER', 'NXFINDES', 'NXHEEL', 'NXHEEDES',
       'NXSENSOR', 'NXSENDES', 'NXTENDON', 'NXTENDES', 'NXPLANTA', 'NXPLADES',
       'NXGAIT', 'NXGAIDES', 'NXOTHER', 'NXOTHSPE', 'NXGENCOM', 'NXABNORM',
       'update_stamp'],
      dtype='object')

In [7]:
clinical = pd.read_csv("ADSP_PHC_COGN.csv").rename(columns={"PHASE":"Phase"})

In [8]:
clinical

,RID,SUBJECT_KEY,Phase,VISCODE,VISCODE2,EXAMDATE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,AGE,DX,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP,update_stamp
0,2,ADNI_011_S_0002,ADNI2,v06,m72,2011-09-19,1,16.0,2,5,80.4682,1.0,0.090,0.002,0.460,0.264,2021-04-14 13:05:55.0
1,2,ADNI_011_S_0002,ADNI2,v21,m96,2013-09-09,1,16.0,2,5,82.4422,1.0,0.288,-0.495,0.460,NaN,2021-04-14 13:05:56.0
2,2,ADNI_011_S_0002,ADNI1,m36,m36,2008-08-27,1,16.0,2,5,77.4073,1.0,0.344,0.419,0.535,NaN,2021-04-14 13:05:56.0
3,2,ADNI_011_S_0002,ADNI2,v41,m120,2015-09-22,1,16.0,2,5,84.4764,1.0,0.382,-0.549,0.595,-0.333,2021-04-14 13:05:56.0
4,2,ADNI_011_S_0002,ADNIGO,m60,m60,2010-09-22,1,16.0,2,5,79.4771,1.0,0.101,0.066,0.620,0.264,2021-04-14 13:05:56.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11383,6850,NaN,ADNI3,sc,sc,2020-01-27,1,19.0,2,5,79.7399,3.0,-0.360,NaN,NaN,NaN,2021-04-14 13:06:13.0
11384,6851,NaN,ADNI3,sc,sc,2020-02-05,2,18.0,2,5,76.5996,2.0,-0.180,NaN,NaN,NaN,2021-04-14 13:06:13.0
11385,6853,NaN,ADNI3,sc,sc,2020-02-04,2,12.0,2,4,67.0910,1.0,1.185,NaN,NaN,NaN,2021-04-14 13:06:13.0
11386,6854,NaN,ADNI3,sc,sc,2020-02-04,1,18.0,2,5,86.2587,3.0,-0.988,NaN,NaN,NaN,2021-04-14 13:06:13.0
11387,6855,NaN,ADNI3,sc,sc,2020-02-05,1,16.0,2,5,74.6804,3.0,-0.814,NaN,NaN,NaN,2021-04-14 13:06:13.0

In [9]:
clinical.head()

,RID,SUBJECT_KEY,Phase,VISCODE,VISCODE2,EXAMDATE,PTGENDER,PTEDUCAT,PTETHCAT,PTRACCAT,AGE,DX,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP,update_stamp
0,2,ADNI_011_S_0002,ADNI2,v06,m72,2011-09-19,1,16.0,2,5,80.4682,1.0,0.090,0.002,0.460,0.264,2021-04-14 13:05:55.0
1,2,ADNI_011_S_0002,ADNI2,v21,m96,2013-09-09,1,16.0,2,5,82.4422,1.0,0.288,-0.495,0.460,NaN,2021-04-14 13:05:56.0
2,2,ADNI_011_S_0002,ADNI1,m36,m36,2008-08-27,1,16.0,2,5,77.4073,1.0,0.344,0.419,0.535,NaN,2021-04-14 13:05:56.0
3,2,ADNI_011_S_0002,ADNI2,v41,m120,2015-09-22,1,16.0,2,5,84.4764,1.0,0.382,-0.549,0.595,-0.333,2021-04-14 13:05:56.0
4,2,ADNI_011_S_0002,ADNIGO,m60,m60,2010-09-22,1,16.0,2,5,79.4771,1.0,0.101,0.066,0.620,0.264,2021-04-14 13:05:56.0

In [10]:
demo

,Phase,ID,RID,SITEID,VISCODE,VISCODE2,USERDATE,USERDATE2,PTSOURCE,PTGENDER,...,PTTLANG,PTPLANG,PTPSPEC,PTCOGBEG,PTMCIBEG,PTADBEG,PTADDX,PTETHCAT,PTRACCAT,update_stamp
0,ADNI1,18,2,107,sc,sc,2005-08-17,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,-4.0,NaN,2.0,5.0,2005-08-17 00:00:00.0
1,ADNI1,20,1,10,f,f,2005-08-18,NaN,1,2.0,...,-4.0,-4.0,-4,NaN,NaN,-4.0,NaN,-4.0,-4.0,2005-08-18 00:00:00.0
2,ADNI1,22,3,107,sc,sc,2005-08-18,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,1999.0,NaN,2.0,5.0,2005-08-18 00:00:00.0
3,ADNI1,24,4,10,sc,sc,2005-08-18,NaN,1,1.0,...,2.0,2.0,-4,NaN,NaN,-4.0,NaN,1.0,5.0,2005-08-18 00:00:00.0
4,ADNI1,26,5,107,sc,sc,2005-08-23,NaN,1,1.0,...,1.0,1.0,-4,NaN,NaN,-4.0,NaN,2.0,5.0,2005-08-23 00:00:00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4757,ADNI3,147284,7029,33,sc,sc,2021-11-22,2021-11-22,1,2.0,...,1.0,1.0,NaN,9999.0,NaN,NaN,9999.0,2.0,4.0,2021-11-23 04:20:20.0
4758,ADNI3,147547,7030,25,sc,sc,2021-11-30,2021-11-30,1,2.0,...,1.0,3.0,Ethiopian,9999.0,NaN,NaN,9999.0,2.0,4.0,2021-11-30 04:19:40.0
4759,ADNI3,147910,7031,25,sc,sc,2021-12-02,2021-12-02,1,2.0,...,1.0,1.0,NaN,2019.0,NaN,NaN,9999.0,2.0,4.0,2021-12-03 04:19:39.0
4760,ADNI3,147946,7032,51,sc,sc,2021-12-03,2021-12-03,1,1.0,...,1.0,1.0,NaN,2018.0,NaN,NaN,9999.0,2.0,5.0,2021-12-04 04:19:40.0
4761,ADNI3,148380,7033,33,sc,sc,2021-12-08,2021-12-08,1,2.0,...,1.0,1.0,NaN,2020.0,NaN,NaN,2021.0,2.0,4.0,2021-12-09 04:19:40.0

In [11]:
diag["Subject"].value_counts()

141_S_1052    4
031_S_0618    4
037_S_0377    4
141_S_1378    4
023_S_0031    4
             ..
067_S_0607    1
036_S_0976    1
013_S_1161    1
022_S_0961    1
016_S_6836    1
Name: Subject, Length: 2646, dtype: int64

In [12]:
comb = pd.read_csv("DXSUM_PDXCONV_ADNIALL.csv")[["RID", "PTID" , "Phase"]]

In [13]:
comb

        RID        PTID  Phase
0         2  011_S_0002  ADNI1
1         2  011_S_0002  ADNI1
2         3  011_S_0003  ADNI1
3         3  011_S_0003  ADNI1
4         3  011_S_0003  ADNI1
...     ...         ...    ...
12850  4785  035_S_4785  ADNI3
12851  6618  011_S_6618  ADNI3
12852  7016  019_S_7016  ADNI3
12853  6960  341_S_6960  ADNI3
12854  6863  022_S_6863  ADNI3

[12855 rows x 3 columns]

In [14]:
m = comb.merge(demo, on = ["RID", "Phase"]).merge(neuro,on = ["RID", "Phase"]).merge(clinical,on = ["RID", "Phase"]).drop_duplicates()

In [15]:
m.columns = [c[:-2] if str(c).endswith(('_x','_y')) else c for c in m.columns]

m = m.loc[:,~m.columns.duplicated()]

In [16]:
m

,RID,PTID,Phase,ID,SITEID,VISCODE,VISCODE2,USERDATE,USERDATE2,PTSOURCE,...,NXOTHSPE,NXGENCOM,NXABNORM,SUBJECT_KEY,AGE,DX,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP
0,2,011_S_0002,ADNI1,18,107,sc,sc,2005-08-17,NaN,1,...,-4,Stacy Schneider GNP,1.0,ADNI_011_S_0002,77.4073,1.0,0.344,0.419,0.535,NaN
1,2,011_S_0002,ADNI1,18,107,sc,sc,2005-08-17,NaN,1,...,-4,Stacy Schneider GNP,1.0,ADNI_011_S_0002,74.4394,1.0,0.277,0.254,0.293,NaN
2,2,011_S_0002,ADNI1,18,107,sc,sc,2005-08-17,NaN,1,...,-4,Stacy Schneider GNP,1.0,ADNI_011_S_0002,74.9295,1.0,0.237,0.278,0.535,-0.333
9,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,82.3655,3.0,-0.973,-1.036,-0.828,0.128
10,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,81.3662,3.0,-1.068,-0.670,-0.516,-0.237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43947,6854,941_S_6854,ADNI3,108346,59,sc,sc,2020-02-06,2020-02-06,1,...,"heel tapping borderline on left, mildly decrea...",NaN,1.0,NaN,86.2587,3.0,-0.988,NaN,NaN,NaN
43950,6725,013_S_6725,ADNI3,81516,10,sc,sc,2019-04-29,2020-09-08,1,...,NaN,NaN,1.0,NaN,80.9801,2.0,0.624,NaN,NaN,NaN
43951,6851,168_S_6851,ADNI3,108476,58,sc,sc,2020-02-07,2020-07-29,1,...,ND,NaN,1.0,NaN,76.5996,2.0,-0.180,NaN,NaN,NaN
43952,6841,035_S_6841,ADNI3,104003,25,sc,sc,2019-12-04,2019-12-06,1,...,NaN,subject DNQ for study,2.0,NaN,74.7598,1.0,0.870,NaN,NaN,NaN
43953,6855,032_S_6855,ADNI3,108591,23,sc,sc,2020-02-10,2020-02-10,1,...,Apraxia,NaN,1.0,NaN,74.6804,3.0,-0.814,NaN,NaN,NaN

In [17]:
diag = diag.rename(columns = {"Subject": "PTID"})

In [18]:
m = m.merge(diag, on = ["PTID", "Phase"])

In [19]:
m

,RID,PTID,Phase,ID,SITEID,VISCODE,VISCODE2,USERDATE,USERDATE2,PTSOURCE,...,NXGENCOM,NXABNORM,SUBJECT_KEY,AGE,DX,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP,Group
0,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,stacy schneider GNP,1.0,G-ADNI-AN000439,82.3655,3.0,-0.973,-1.036,-0.828,0.128,2.0
1,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,stacy schneider GNP,1.0,G-ADNI-AN000439,81.3662,3.0,-1.068,-0.670,-0.516,-0.237,2.0
2,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,stacy schneider GNP,1.0,G-ADNI-AN000439,83.3648,3.0,-1.559,-0.645,-0.756,NaN,2.0
3,3,011_S_0003,ADNI1,22,107,sc,sc,2005-08-18,NaN,1,...,stacy schneider GNP,1.0,G-ADNI-AN000439,81.8645,3.0,-0.768,-0.145,-0.516,-0.305,2.0
4,4,022_S_0004,ADNI1,24,10,sc,sc,2005-08-18,NaN,1,...,-4,1.0,G-ADNI-AN000446,69.3634,2.0,0.280,-0.662,0.362,-0.868,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,6854,941_S_6854,ADNI3,108346,59,sc,sc,2020-02-06,2020-02-06,1,...,NaN,1.0,NaN,86.2587,3.0,-0.988,NaN,NaN,NaN,2.0
7609,6725,013_S_6725,ADNI3,81516,10,sc,sc,2019-04-29,2020-09-08,1,...,NaN,1.0,NaN,80.9801,2.0,0.624,NaN,NaN,NaN,1.0
7610,6851,168_S_6851,ADNI3,108476,58,sc,sc,2020-02-07,2020-07-29,1,...,NaN,1.0,NaN,76.5996,2.0,-0.180,NaN,NaN,NaN,1.0
7611,6841,035_S_6841,ADNI3,104003,25,sc,sc,2019-12-04,2019-12-06,1,...,subject DNQ for study,2.0,NaN,74.7598,1.0,0.870,NaN,NaN,NaN,0.0
7612,6855,032_S_6855,ADNI3,108591,23,sc,sc,2020-02-10,2020-02-10,1,...,NaN,1.0,NaN,74.6804,3.0,-0.814,NaN,NaN,NaN,2.0

In [20]:
m["PTID"].value_counts()

067_S_4767    18
141_S_0697    15
067_S_4072    14
094_S_1417    14
003_S_1122    14
              ..
109_S_5255     1
053_S_5281     1
082_S_5279     1
072_S_4056     1
032_S_6855     1
Name: PTID, Length: 2408, dtype: int64

In [21]:
t = m

In [22]:
t = t.drop(["ID",  "SITEID", "VISCODE", "VISCODE2", "USERDATE", "USERDATE2",
            "update_stamp",  "PTSOURCE", "PTDOBMM","DX"], axis=1)

In [23]:
t.columns

Index(['RID', 'PTID', 'Phase', 'PTGENDER', 'PTDOBYY', 'PTHAND', 'PTMARRY',
       'PTEDUCAT', 'PTWORKHS', 'PTWORK', 'PTWRECNT', 'PTNOTRT', 'PTRTYR',
       'PTHOME', 'PTOTHOME', 'PTTLANG', 'PTPLANG', 'PTPSPEC', 'PTCOGBEG',
       'PTMCIBEG', 'PTADBEG', 'PTADDX', 'PTETHCAT', 'PTRACCAT', 'EXAMDATE',
       'NXVISUAL', 'NXVISDES', 'NXAUDITO', 'NXAUDDES', 'NXTREMOR', 'NXTREDES',
       'NXCONSCI', 'NXCONDES', 'NXNERVE', 'NXNERDES', 'NXMOTOR', 'NXMOTDES',
       'NXFINGER', 'NXFINDES', 'NXHEEL', 'NXHEEDES', 'NXSENSOR', 'NXSENDES',
       'NXTENDON', 'NXTENDES', 'NXPLANTA', 'NXPLADES', 'NXGAIT', 'NXGAIDES',
       'NXOTHER', 'NXOTHSPE', 'NXGENCOM', 'NXABNORM', 'SUBJECT_KEY', 'AGE',
       'PHC_MEM', 'PHC_EXF', 'PHC_LAN', 'PHC_VSP', 'Group'],
      dtype='object')

In [24]:
t

,RID,PTID,Phase,PTGENDER,PTDOBYY,PTHAND,PTMARRY,PTEDUCAT,PTWORKHS,PTWORK,...,NXOTHSPE,NXGENCOM,NXABNORM,SUBJECT_KEY,AGE,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP,Group
0,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,-4.0,chemical engineer,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,82.3655,-0.973,-1.036,-0.828,0.128,2.0
1,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,-4.0,chemical engineer,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,81.3662,-1.068,-0.670,-0.516,-0.237,2.0
2,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,-4.0,chemical engineer,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,83.3648,-1.559,-0.645,-0.756,NaN,2.0
3,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,-4.0,chemical engineer,...,-4,stacy schneider GNP,1.0,G-ADNI-AN000439,81.8645,-0.768,-0.145,-0.516,-0.305,2.0
4,4,022_S_0004,ADNI1,1.0,1938.0,1.0,1.0,10.0,-4.0,Raw Material Analyzin,...,-4,-4,1.0,G-ADNI-AN000446,69.3634,0.280,-0.662,0.362,-0.868,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,6854,941_S_6854,ADNI3,1.0,1933.0,1.0,1.0,18.0,1.0,architect,...,"heel tapping borderline on left, mildly decrea...",NaN,1.0,NaN,86.2587,-0.988,NaN,NaN,NaN,2.0
7609,6725,013_S_6725,ADNI3,1.0,1938.0,1.0,3.0,20.0,1.0,Anesthesiologist,...,NaN,NaN,1.0,NaN,80.9801,0.624,NaN,NaN,NaN,1.0
7610,6851,168_S_6851,ADNI3,2.0,1943.0,1.0,3.0,18.0,1.0,Economist state government,...,ND,NaN,1.0,NaN,76.5996,-0.180,NaN,NaN,NaN,1.0
7611,6841,035_S_6841,ADNI3,2.0,1945.0,1.0,1.0,14.0,1.0,sales,...,NaN,subject DNQ for study,2.0,NaN,74.7598,0.870,NaN,NaN,NaN,0.0
7612,6855,032_S_6855,ADNI3,1.0,1945.0,1.0,1.0,16.0,1.0,Computer software analyst/ consultant,...,Apraxia,NaN,1.0,NaN,74.6804,-0.814,NaN,NaN,NaN,2.0

In [25]:
t = t.fillna(-4)
t = t.replace("-4", -4)
cols_to_delete = t.columns[(t == -4).sum()/len(t) > .70]
t.drop(cols_to_delete, axis = 1, inplace = True)

In [26]:
len(t.columns)

41

In [27]:
t["PTWORK"] = t["PTWORK"].str.lower().str.replace("housewife", "homemaker").str.replace("rn", "nurse").str.replace("bookeeper",
                                                                                                                   "bookkeeper").str.replace("cpa", "accounting")

In [28]:
t["PTWORK"] = t["PTWORK"].fillna("-4").astype(str)

In [29]:
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*teach.*$)', 'education')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*bookkeep.*$)', 'bookkeeper')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*wife.*$)', 'homemaker')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*educat.*$)', 'education')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*engineer.*$)', 'engineer')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*eingineering.*$)', 'engineer') 
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*computer programmer.*$)', 'engineer') 
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*nurs.*$)', 'nurse')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*manage.*$)', 'managment')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*therapist.*$)', 'therapist')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*sales.*$)', 'sales')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*admin.*$)', 'admin')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*account.*$)', 'accounting')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*real.*$)', 'real estate')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*secretary.*$)', 'secretary')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*professor.*$)', 'professor')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*chem.*$)', 'chemist')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*business.*$)', 'business')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*writ.*$)', 'writing')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*psych.*$)', 'psychology')
t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*analys.*$)', 'analyst')

/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*teach.*$)', 'education')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*bookkeep.*$)', 'bookkeeper')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*wife.*$)', 'homemaker')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*educat.*$)', 'education')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:5: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*engineer.*$)', 'engineer')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*eingineering.*$)', 'engineer')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:7: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*computer programmer.*$)', 'engineer')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:8: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*nurs.*$)', 'nurse')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:9: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*manage.*$)', 'managment')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*therapist.*$)', 'therapist')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:11: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*sales.*$)', 'sales')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:12: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*admin.*$)', 'admin')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*account.*$)', 'accounting')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:14: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*real.*$)', 'real estate')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:15: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*secretary.*$)', 'secretary')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:16: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*professor.*$)', 'professor')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:17: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*chem.*$)', 'chemist')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:18: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*business.*$)', 'business')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:19: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*writ.*$)', 'writing')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:20: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*psych.*$)', 'psychology')
/var/folders/z8/84l73v2d6jb2m3fzdf560ft80000gq/T/ipykernel_88669/2309654543.py:21: FutureWarning: The default value of regex will change from True to False in a future version.
  t['PTWORK'] = t['PTWORK'].str.replace(r'(^.*analys.*$)', 'analyst')

In [30]:
cond = t['PTWORK'].value_counts()
threshold = 10
t['PTWORK'] = np.where(t['PTWORK'].isin(cond.index[cond >= threshold ]), t['PTWORK'], 'other')

In [31]:
categorical = ['PTGENDER', 'PTWORK',
 'PTHOME',
 'PTMARRY',
 'PTEDUCAT',
 'PTPLANG',
 'NXVISUAL',
 'PTNOTRT',
 'NXTREMOR',
 'NXAUDITO',
 'PTHAND']

In [32]:
quant = ['PTDOBYY',
 'PHC_MEM',
 'PHC_EXF',
 'PTRACCAT',
 'AGE',
 'PTADDX',
 'PTETHCAT',
 'PTCOGBEG',
 'PHC_VSP',
 'PHC_LAN']

In [33]:
text = ["PTWORK", "CMMED"]

In [34]:
cols_left = list(set(t.columns) - set(categorical) - set(text)  - set(["label", "Group","GROUP", "Phase", "RID", "PTID"]))
t[cols_left]

,PTADDX,PTETHCAT,PTDOBYY,NXGAIT,PHC_LAN,NXTENDON,PTCOGBEG,EXAMDATE,SUBJECT_KEY,NXPLANTA,...,PTRTYR,NXCONSCI,NXOTHER,PTWRECNT,PHC_EXF,NXABNORM,NXMOTOR,PTTLANG,PTRACCAT,NXFINGER
0,-4.0,2.0,1924.0,1.0,-0.828,1.0,-4.0,2005-08-18,G-ADNI-AN000439,1.0,...,9/18/1989,1.0,1.0,chemical engineer,-1.036,1.0,1.0,1.0,5.0,1.0
1,-4.0,2.0,1924.0,1.0,-0.516,1.0,-4.0,2005-08-18,G-ADNI-AN000439,1.0,...,9/18/1989,1.0,1.0,chemical engineer,-0.670,1.0,1.0,1.0,5.0,1.0
2,-4.0,2.0,1924.0,1.0,-0.756,1.0,-4.0,2005-08-18,G-ADNI-AN000439,1.0,...,9/18/1989,1.0,1.0,chemical engineer,-0.645,1.0,1.0,1.0,5.0,1.0
3,-4.0,2.0,1924.0,1.0,-0.516,1.0,-4.0,2005-08-18,G-ADNI-AN000439,1.0,...,9/18/1989,1.0,1.0,chemical engineer,-0.145,1.0,1.0,1.0,5.0,1.0
4,-4.0,1.0,1938.0,1.0,0.362,1.0,-4.0,2005-08-18,G-ADNI-AN000446,1.0,...,-4,1.0,1.0,Mechanic,-0.662,1.0,1.0,2.0,5.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,2017.0,2.0,1933.0,2.0,-4.000,1.0,2013.0,-4,-4,-4.0,...,2008-xx-xx,1.0,2.0,architecture professor,-4.000,1.0,1.0,1.0,5.0,1.0
7609,9999.0,2.0,1938.0,1.0,-4.000,1.0,2017.0,-4,-4,1.0,...,2009-xx-xx,1.0,1.0,Anesthesiologist,-4.000,1.0,1.0,1.0,5.0,1.0
7610,9999.0,2.0,1943.0,2.0,-4.000,2.0,2009.0,-4,-4,1.0,...,2009-xx-xx,1.0,-4.0,Economist state government,-4.000,1.0,1.0,1.0,5.0,1.0
7611,-4.0,2.0,1945.0,-4.0,-4.000,-4.0,2014.0,-4,-4,-4.0,...,2019-02-xx,-4.0,-4.0,conpanion,-4.000,2.0,-4.0,1.0,5.0,-4.0
7612,2019.0,2.0,1945.0,1.0,-4.000,1.0,2019.0,-4,-4,1.0,...,2007-11-30,1.0,2.0,real estate broker,-4.000,1.0,1.0,1.0,5.0,2.0

In [35]:
for col in cols_left:
    if len(t[col].value_counts()) < 10:
        print(col)
        categorical.append(col)

PTETHCAT
NXGAIT
NXTENDON
NXPLANTA
NXNERVE
NXSENSOR
NXHEEL
NXCONSCI
NXOTHER
NXABNORM
NXMOTOR
PTTLANG
PTRACCAT
NXFINGER

In [36]:
to_del = ["PTRTYR", "EXAMDATE", "SUBJECT_KEY", "PTWRECNT"]
t = t.drop(to_del, axis=1)

In [37]:
quant = list(set(cols_left) - set(categorical) - set(text)  -set(to_del) - set(["label", "Group","GROUP", "Phase", "RID", "PTID"]))
t[quant]

      PTADDX  PHC_MEM  PTDOBYY  PHC_EXF  PHC_LAN  PTCOGBEG  PHC_VSP      AGE
0       -4.0   -0.973   1924.0   -1.036   -0.828      -4.0    0.128  82.3655
1       -4.0   -1.068   1924.0   -0.670   -0.516      -4.0   -0.237  81.3662
2       -4.0   -1.559   1924.0   -0.645   -0.756      -4.0   -4.000  83.3648
3       -4.0   -0.768   1924.0   -0.145   -0.516      -4.0   -0.305  81.8645
4       -4.0    0.280   1938.0   -0.662    0.362      -4.0   -0.868  69.3634
...      ...      ...      ...      ...      ...       ...      ...      ...
7608  2017.0   -0.988   1933.0   -4.000   -4.000    2013.0   -4.000  86.2587
7609  9999.0    0.624   1938.0   -4.000   -4.000    2017.0   -4.000  80.9801
7610  9999.0   -0.180   1943.0   -4.000   -4.000    2009.0   -4.000  76.5996
7611    -4.0    0.870   1945.0   -4.000   -4.000    2014.0   -4.000  74.7598
7612  2019.0   -0.814   1945.0   -4.000   -4.000    2019.0   -4.000  74.6804

[7613 rows x 8 columns]

In [38]:
cols_left = list(set(cols_left) - set(categorical) - set(text) - set(quant) - set(to_del))

In [39]:
t

,RID,PTID,Phase,PTGENDER,PTDOBYY,PTHAND,PTMARRY,PTEDUCAT,PTWORK,PTNOTRT,...,NXPLANTA,NXGAIT,NXOTHER,NXABNORM,AGE,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP,Group
0,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,1.0,...,1.0,1.0,1.0,1.0,82.3655,-0.973,-1.036,-0.828,0.128,2.0
1,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,1.0,...,1.0,1.0,1.0,1.0,81.3662,-1.068,-0.670,-0.516,-0.237,2.0
2,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,1.0,...,1.0,1.0,1.0,1.0,83.3648,-1.559,-0.645,-0.756,-4.000,2.0
3,3,011_S_0003,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,1.0,...,1.0,1.0,1.0,1.0,81.8645,-0.768,-0.145,-0.516,-0.305,2.0
4,4,022_S_0004,ADNI1,1.0,1938.0,1.0,1.0,10.0,other,0.0,...,1.0,1.0,1.0,1.0,69.3634,0.280,-0.662,0.362,-0.868,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,6854,941_S_6854,ADNI3,1.0,1933.0,1.0,1.0,18.0,architect,1.0,...,-4.0,2.0,2.0,1.0,86.2587,-0.988,-4.000,-4.000,-4.000,2.0
7609,6725,013_S_6725,ADNI3,1.0,1938.0,1.0,3.0,20.0,other,1.0,...,1.0,1.0,1.0,1.0,80.9801,0.624,-4.000,-4.000,-4.000,1.0
7610,6851,168_S_6851,ADNI3,2.0,1943.0,1.0,3.0,18.0,nurse,1.0,...,1.0,2.0,-4.0,1.0,76.5996,-0.180,-4.000,-4.000,-4.000,1.0
7611,6841,035_S_6841,ADNI3,2.0,1945.0,1.0,1.0,14.0,sales,1.0,...,-4.0,-4.0,-4.0,2.0,74.7598,0.870,-4.000,-4.000,-4.000,0.0
7612,6855,032_S_6855,ADNI3,1.0,1945.0,1.0,1.0,16.0,analyst,1.0,...,1.0,1.0,2.0,1.0,74.6804,-0.814,-4.000,-4.000,-4.000,2.0

In [54]:
#after reviewing the meaning of each column, these are the final ones
l = ['RID', 'PTID', 'Group', 'Phase', 'PTGENDER', 'PTDOBYY', 'PTHAND',
       'PTMARRY', 'PTEDUCAT', 'PTWORK', 'PTNOTRT', 'PTHOME', 'PTTLANG',
       'PTPLANG', 'PTCOGBEG', 'PTETHCAT', 'PTRACCAT', 'NXVISUAL',
       'NXAUDITO', 'NXTREMOR', 'NXCONSCI', 'NXNERVE', 'NXMOTOR', 'NXFINGER',
       'NXHEEL', 'NXSENSOR', 'NXTENDON', 'NXPLANTA', 'NXGAIT', 
       'NXABNORM',  'PHC_MEM', 'PHC_EXF', 'PHC_LAN', 'PHC_VSP']

In [55]:
t[l]

,RID,PTID,Group,Phase,PTGENDER,PTDOBYY,PTHAND,PTMARRY,PTEDUCAT,PTWORK,...,NXHEEL,NXSENSOR,NXTENDON,NXPLANTA,NXGAIT,NXABNORM,PHC_MEM,PHC_EXF,PHC_LAN,PHC_VSP
0,3,011_S_0003,2.0,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,...,1.0,1.0,1.0,1.0,1.0,1.0,-0.973,-1.036,-0.828,0.128
1,3,011_S_0003,2.0,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,...,1.0,1.0,1.0,1.0,1.0,1.0,-1.068,-0.670,-0.516,-0.237
2,3,011_S_0003,2.0,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,...,1.0,1.0,1.0,1.0,1.0,1.0,-1.559,-0.645,-0.756,-4.000
3,3,011_S_0003,2.0,ADNI1,1.0,1924.0,1.0,1.0,18.0,engineer,...,1.0,1.0,1.0,1.0,1.0,1.0,-0.768,-0.145,-0.516,-0.305
4,4,022_S_0004,1.0,ADNI1,1.0,1938.0,1.0,1.0,10.0,other,...,1.0,1.0,1.0,1.0,1.0,1.0,0.280,-0.662,0.362,-0.868
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,6854,941_S_6854,2.0,ADNI3,1.0,1933.0,1.0,1.0,18.0,architect,...,1.0,1.0,1.0,-4.0,2.0,1.0,-0.988,-4.000,-4.000,-4.000
7609,6725,013_S_6725,1.0,ADNI3,1.0,1938.0,1.0,3.0,20.0,other,...,1.0,1.0,1.0,1.0,1.0,1.0,0.624,-4.000,-4.000,-4.000
7610,6851,168_S_6851,1.0,ADNI3,2.0,1943.0,1.0,3.0,18.0,nurse,...,1.0,1.0,2.0,1.0,2.0,1.0,-0.180,-4.000,-4.000,-4.000
7611,6841,035_S_6841,0.0,ADNI3,2.0,1945.0,1.0,1.0,14.0,sales,...,-4.0,-4.0,-4.0,-4.0,-4.0,2.0,0.870,-4.000,-4.000,-4.000
7612,6855,032_S_6855,2.0,ADNI3,1.0,1945.0,1.0,1.0,16.0,analyst,...,1.0,1.0,1.0,1.0,1.0,1.0,-0.814,-4.000,-4.000,-4.000

In [56]:
t.to_csv("uncat_clinical.csv")

In [57]:
dfs = []

In [58]:
for col in categorical:
    dfs.append(pd.get_dummies(t[col], prefix = col))

In [59]:
cat = pd.concat(dfs, axis=1)

In [60]:
t[quant]

      PTADDX  PHC_MEM  PTDOBYY  PHC_EXF  PHC_LAN  PTCOGBEG  PHC_VSP      AGE
0       -4.0   -0.973   1924.0   -1.036   -0.828      -4.0    0.128  82.3655
1       -4.0   -1.068   1924.0   -0.670   -0.516      -4.0   -0.237  81.3662
2       -4.0   -1.559   1924.0   -0.645   -0.756      -4.0   -4.000  83.3648
3       -4.0   -0.768   1924.0   -0.145   -0.516      -4.0   -0.305  81.8645
4       -4.0    0.280   1938.0   -0.662    0.362      -4.0   -0.868  69.3634
...      ...      ...      ...      ...      ...       ...      ...      ...
7608  2017.0   -0.988   1933.0   -4.000   -4.000    2013.0   -4.000  86.2587
7609  9999.0    0.624   1938.0   -4.000   -4.000    2017.0   -4.000  80.9801
7610  9999.0   -0.180   1943.0   -4.000   -4.000    2009.0   -4.000  76.5996
7611    -4.0    0.870   1945.0   -4.000   -4.000    2014.0   -4.000  74.7598
7612  2019.0   -0.814   1945.0   -4.000   -4.000    2019.0   -4.000  74.6804

[7613 rows x 8 columns]

In [61]:
cat

,PTGENDER_-4.0,PTGENDER_1.0,PTGENDER_2.0,PTWORK_-4,PTWORK_accounting,PTWORK_admin,PTWORK_analyst,PTWORK_architect,PTWORK_army officer,PTWORK_artist,...,PTRACCAT_1.0,PTRACCAT_2.0,PTRACCAT_3.0,PTRACCAT_4.0,PTRACCAT_5.0,PTRACCAT_6.0,PTRACCAT_7.0,NXFINGER_-4.0,NXFINGER_1.0,NXFINGER_2.0
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,1,0
7609,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
7610,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
7611,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7612,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [62]:
t[["PTID","RID", "Phase", "Group"]]

            PTID   RID  Phase  Group
0     011_S_0003     3  ADNI1    2.0
1     011_S_0003     3  ADNI1    2.0
2     011_S_0003     3  ADNI1    2.0
3     011_S_0003     3  ADNI1    2.0
4     022_S_0004     4  ADNI1    1.0
...          ...   ...    ...    ...
7608  941_S_6854  6854  ADNI3    2.0
7609  013_S_6725  6725  ADNI3    1.0
7610  168_S_6851  6851  ADNI3    1.0
7611  035_S_6841  6841  ADNI3    0.0
7612  032_S_6855  6855  ADNI3    2.0

[7613 rows x 4 columns]

In [63]:
c = pd.concat([t[["PTID", "RID", "Phase", "Group"]].reset_index(), cat.reset_index(), t[quant].reset_index()], axis=1).drop("index", axis=1) #tex

In [64]:
c

,PTID,RID,Phase,Group,PTGENDER_-4.0,PTGENDER_1.0,PTGENDER_2.0,PTWORK_-4,PTWORK_accounting,PTWORK_admin,...,NXFINGER_1.0,NXFINGER_2.0,PTADDX,PHC_MEM,PTDOBYY,PHC_EXF,PHC_LAN,PTCOGBEG,PHC_VSP,AGE
0,011_S_0003,3,ADNI1,2.0,0,1,0,0,0,0,...,1,0,-4.0,-0.973,1924.0,-1.036,-0.828,-4.0,0.128,82.3655
1,011_S_0003,3,ADNI1,2.0,0,1,0,0,0,0,...,1,0,-4.0,-1.068,1924.0,-0.670,-0.516,-4.0,-0.237,81.3662
2,011_S_0003,3,ADNI1,2.0,0,1,0,0,0,0,...,1,0,-4.0,-1.559,1924.0,-0.645,-0.756,-4.0,-4.000,83.3648
3,011_S_0003,3,ADNI1,2.0,0,1,0,0,0,0,...,1,0,-4.0,-0.768,1924.0,-0.145,-0.516,-4.0,-0.305,81.8645
4,022_S_0004,4,ADNI1,1.0,0,1,0,0,0,0,...,1,0,-4.0,0.280,1938.0,-0.662,0.362,-4.0,-0.868,69.3634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7608,941_S_6854,6854,ADNI3,2.0,0,1,0,0,0,0,...,1,0,2017.0,-0.988,1933.0,-4.000,-4.000,2013.0,-4.000,86.2587
7609,013_S_6725,6725,ADNI3,1.0,0,1,0,0,0,0,...,1,0,9999.0,0.624,1938.0,-4.000,-4.000,2017.0,-4.000,80.9801
7610,168_S_6851,6851,ADNI3,1.0,0,0,1,0,0,0,...,1,0,9999.0,-0.180,1943.0,-4.000,-4.000,2009.0,-4.000,76.5996
7611,035_S_6841,6841,ADNI3,0.0,0,0,1,0,0,0,...,0,0,-4.0,0.870,1945.0,-4.000,-4.000,2014.0,-4.000,74.7598
7612,032_S_6855,6855,ADNI3,2.0,0,1,0,0,0,0,...,0,1,2019.0,-0.814,1945.0,-4.000,-4.000,2019.0,-4.000,74.6804

In [65]:
#removing repeating subjects, taking the most recent diagnosis
c = c.groupby('PTID', 
                  group_keys=False).apply(lambda x: x.loc[x["Group"].astype(int).idxmax()]).drop("PTID", axis = 1).reset_index(inplace=False)

In [87]:
c.to_csv("clinical.csv")